# Generated by Django 4.0.4 on 2022-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('credits', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
